### ISSUE TITLE
scollToIndex out of range

### ISSUE THREAD

**Issue by daghass** [KPS250/React-Native-FlatList-Slider#2] opened 2020-08-04 08:49 UTC
Hi thanks for the great component but i'm receiving scrollToIndex out of range specially when i move to another tab using react-navigation bottom tabs 
![0c9849af-8bb0-4cff-8966-bc564782479a](https://user-images.githubusercontent.com/44110742/89273628-79f04400-d648-11ea-8a40-d5d27f3afbee.jpg)

**Comment by KPS250** [comment] 2020-08-06 18:20
@daghass Seems it out of bounds exception. Is data getting changed on tab change? It's hard to guess whats the issue with the screenshot. It would be great if you could share sample code of link to the repo to reproduce the issue.

**Comment by hbittar** [comment] 2020-08-08 21:38
I have the same problem

            <FlatListSlider
              data={images}
              imageKey={'banner'}
              local
              width={90}
              height={60}
              indicator={false}
            />

**Comment by ManalLiaquat** [comment] 2020-08-13 16:58
I am also getting the same error, this is because of changing num of columns in `numColumns` prop on the go. Flatlist don't support this numColumns should be constant

**Comment by KPS250** [comment] 2020-08-18 14:32
@ManalLiaquat @daghass @hbittar I was able to reproduce the issue and it occurs when loop={false}. Working on it now. Will update the library soon.

**Comment by KPS250** [comment] 2020-08-18 16:38
@ManalLiaquat @daghass @hbittar I have pushed V1.0.2 with the fix. You can try updating the library. Closing this issue.

**Closed as completed by KPS250** 2020-08-18 16:38 UTC
